version: "2.2"

services:
  mysql:
    image: mysql:8.2
    restart: always 
    ports:
      - "3306:3306" 
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
 
  postgres:
    image: postgres:16.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
      - postgres

  petclinic-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8070:8085"  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/petclinic  # Update port in JDBC URL
      - SPRING_DATASOURCE_USERNAME=petclinic
      - SPRING_DATASOURCE_PASSWORD=petclinic
      - SPRING_PROFILES_ACTIVE=mysql  # Set the active Spring profile
    depends_on:
      - mysql
